### PR TITLE
Tweaks for vcf2maf dockerfiles

### PR DESCRIPTION
**Pull request by ckandoth**

### CODE REVIEW

**Comment by lordzappo** [comment]
add to whitelist

**Comment by nikhil** [comment]
This actually passed Jenkins just overwrote this

**Comment by ckandoth** [comment]
Need to merge this with the latest dev which removes old tools from the VM, so the builds don't run out of disk space.

**Comment by nikhil** [comment]
Had to kill it to get my PR in, will rerun this PR later

**Pull request merged**
