### PR TITLE
ngs-filters 1.2, delete bugged abra versions from build, fix picard 1…

### PR DESCRIPTION
**Pull request by lordzappo**
….96 default bug

### CODE REVIEW

**Comment by lordzappo** [comment]
test this please

**Comment by lordzappo** [comment]
test this please

**Comment by lordzappo** [comment]
test this please

**Comment by ckandoth** [comment]
The changes from this PR that are still applicable have been redone on a fork of the latest dev branch. The new PR is #170 and imma close this one. CC @nikhil @lordzappo

**Pull request closed without merging**
